# Generated by Django 3.2.7 on 2021-12-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0012_auto_20211206_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='photo',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(choices=[('Unlike', 'Unlike'), ('Like', 'Like')], default='like', max_length=10),
        ),
    ]
